#!/bin/bash -e

trap "tput sgr0" EXIT

function usage() {
    echo "Usage: $0 OPTION VALUE"
    echo ""
    echo "Downloads and starts a replicating cluster of mysql instances for testing purposes."
    echo "A cluster comprises of a single master and a configurable number of slaves."
    echo ""
    echo "Long live docker!"
    echo "http://www.docker.com/"
    echo ""
    echo "Options:"
    echo "  -n  the number of slave instances to create (min 1)"
    echo "" 
    exit 1
}

while getopts ":n:" opt; do
  case $opt in
    n)
      num_slaves=$OPTARG
      ;;
    \?)
      echo -e '\x1B[1;31m'
      echo "Invalid option: -$OPTARG" >&2
      usage
      ;;
    :)
      echo -e '\x1B[1;31m'
      echo "Option -$OPTARG requires an argument." >&2
      usage
      ;;
  esac
done

if ! [[ $num_slaves =~ ^-?[0-9]+$ ]]
then
  echo -e '\x1B[1;31m'
  usage
fi

if ! docker ps > /dev/null 2>&1
then 
  echo -e '\x1B[1;31m'
  echo "Docker needs to be installed and running." >&2
  echo "Try:"
  echo "  sudo apt-get install docker-io"
  echo "  or"
  echo "  sudo yum install docker-io"
  echo ""
  echo "See https://docs.docker.com/installation"
  echo ""
  exit 1
fi

dockermysqlslave=""

function dockermysqlslavelinks() {
  dockermysqlslave="docker run --rm --link master:master "
  for (( i=1; i<=${1}; i++ ))
  do
    dockermysqlslave+="--link slave$i:slave$i "
  done
  dockermysqlslave+="doug/mysql-client mysql"
}

function start_slave() {
  echo "starting slave ${1}"
  docker run -d -e SERVER_ID=${1} -e MYSQL_MASTER_HOST=master --link master:master --name slave${1} doug/mysql-slave
  slave_output_docker+="${dockermysqlslave} -uroot -proot -h slave${1} -e \"select * from cluster_test.pets\"\n"
  return $?
}

function start_master() {
  echo "starting master"
  docker run -d --name master doug/mysql-master
  return $?
}

start_master

dockermysqlslavelinks $num_slaves
for (( i=1; i<=$num_slaves; i++ ))
do
  start_slave $i
done


output+="##############################################\n"
output+="\n"
output+="Your replicating cluster is ready to go!\n"
output+="Connect to it from within another container:\n"
output+="docker run --rm --link master:master doug/mysql-client mysql -uroot -proot -h master -e \"create database cluster_test;\"\n"
output+="docker run --rm --link master:master doug/mysql-client mysql -uroot -proot -h master -e \"create table cluster_test.pets(name varchar(25));\"\n"
output+="docker run --rm --link master:master doug/mysql-client mysql -uroot -proot -h master -e \"insert into cluster_test.pets values('fido');\"\n"
output+="$slave_output_docker"
output+="docker run --rm --link master:master doug/mysql-client mysql -uroot -proot -h master -e \"drop database cluster_test;\"\n\n"
output+="##############################################\n"
echo -e '\x1B[1;36m'"${output}"
